$background = rgba(050505ff)
$error = rgba(ff1744ff)
$error_container = rgba(3b0000ff)
$inverse_on_surface = rgba(1d1b20ff)
$inverse_primary = rgba(8b0000ff)
$inverse_surface = rgba(0a0a0aff)
$on_background = rgba(ccccccff)
$on_error = rgba(ff0000ff)
$on_error_container = rgba(ff4444ff)
$on_primary = rgba(ccccccff)
$on_primary_container = rgba(ccccccff)
$on_primary_fixed = rgba(8b0000ff)
$on_primary_fixed_variant = rgba(660000ff)
$on_secondary = rgba(ccccccff)
$on_secondary_container = rgba(ccccccff)
$on_secondary_fixed = rgba(2d2d2dff)
$on_secondary_fixed_variant = rgba(1a1a1aff)
$on_surface = rgba(ccccccff)
$on_surface_variant = rgba(999999ff)
$on_tertiary = rgba(ccccccff)
$on_tertiary_container = rgba(ccccccff)
$on_tertiary_fixed = rgba(2d2d2dff)
$on_tertiary_fixed_variant = rgba(1a1a1aff)
$outline = rgba(333333ff)
$outline_variant = rgba(222222ff)
$primary = rgba(8b0000ff)
$primary_container = rgba(1a0505ff)
$primary_fixed = rgba(660000ff)
$primary_fixed_dim = rgba(440000ff)
$scrim = rgba(000000ff)
$secondary = rgba(2d2d2dff)
$secondary_container = rgba(1a1a1aff)
$secondary_fixed = rgba(333333ff)
$secondary_fixed_dim = rgba(252525ff)
$shadow = rgba(000000ff)
$source_color = rgba(8b0000ff)
$surface = rgba(050505ff)
$surface_bright = rgba(0a0a0aff)
$surface_container = rgba(1a1a1aff)
$surface_container_high = rgba(222222ff)
$surface_container_highest = rgba(2d2d2dff)
$surface_container_low = rgba(050505ff)
$surface_container_lowest = rgba(000000ff)
$surface_dim = rgba(050505ff)
$surface_tint = rgba(8b0000ff)
$surface_variant = rgba(1a1a1aff)
$tertiary = rgba(2d2d2dff)
$tertiary_container = rgba(1a1a1aff)
$tertiary_fixed = rgba(333333ff)
$tertiary_fixed_dim = rgba(252525ff)
$active_border = rgba(8b0000ff)
$inactive_border = rgba(1a1a1aff)
